### ISSUE TITLE
How to reset ID.

### ISSUE THREAD

**Issue by matrpedreira** [deano2390/MaterialShowcaseView#15]
I want to give the option for the user to show the tutorial again if he wants. From what I understood I would have to remove the IDs from the place they are stored. Is there a good way to do that?

**Comment by deano2390** [comment]
To reset a single Showcase use the static reset method:

```` 
MaterialShowcaseView.resetSingleUse(context, "your_showcase_id");
````

Or you can reset all of your showcase views with the static reset all method:

````
 MaterialShowcaseView.resetAll(this);

**Comment by matrpedreira** [comment]
Thx.
