### ISSUE TITLE
Customize ShowcaseView background color

### ISSUE THREAD

**Issue by alinalihassan** [deano2390/MaterialShowcaseView#17]
It would be better if we could customize at least the color if not also the transparency of the ShowcaseView.

**Comment by MFlisar** [comment]
You can, for example like following (transparent light gray):

    MaterialShowcaseView.Builder builder = new MaterialShowcaseView.Builder(activity)
        .setMaskColour(Color.argb(150, 0, 0, 0));

**Comment by superalin98** [comment]
Thanks, I will try

**Comment by balavishnu** [comment]
How do we do the same for Sequence?

**Comment by balavishnu** [comment]
Figured it out myself

 ShowcaseConfig config = new ShowcaseConfig();
        config.setDelay(200); 
        config.setMaskColor(Color.argb(150, 0, 0, 0));

**Comment by Lurzapps** [comment]
setMaskColor wont work for me in ShowcaseSequence!

**Comment by vkotovv** [comment]
@Lurzapps I think there is a bug in MaterialShowcaseView class. It checks if mask color is set in config, but  `Color.argb(150, 0, 0, 0)` returns negative value. See this code:
```
        if(config.getMaskColor() > 0){
            setMaskColour(config.getMaskColor());
        }
```

**Comment by tamnuwat** [comment]
How to set a dissmiss button color ?
