### ISSUE TITLE
how to change background color of showcaseview

### ISSUE THREAD

**Issue by Vipul-StoryDigital** [deano2390/MaterialShowcaseView#184]
I am trying to change the background color of the showcase view, and I used  
{
setMaskColor(100,0,0,0)//black
}
but there is no reflection of the black color. it takes default color.
please help how to set the black color into the background of showcase view.

**Comment by Ryanhustler420** [comment]
`.setMaskColour(getResources().getColor(R.color.colorAccent))`

**Comment by Ryanhustler420** [comment]
Closes Vipul-StoryDigital/MaterialShowcaseView#184

**Comment by Ryanhustler420** [comment]
Fixes #184

**Comment by IndiDaFunk** [comment]
.setMaskColour(getResources().getColor(R.color.colorAccent)) ....This isn't working for me..

**Comment by bhoomit11** [comment]
> getResources().getColor(R.color.colorAccent)) .

Same problem

**Comment by bhoomit11** [comment]
> .setMaskColour(getResources().getColor(R.color.colorAccent)) ....This isn't working for me..

Same problem, not working :(

**Comment by mohammadrezaberenji** [comment]
@Ryanhustler420 @bhoomit11  use ContextCompat.getColor(this, R.color.showCaseMask) for settting mask color. this works for me
