### ISSUE TITLE
Reset all Showcases at once

### ISSUE THREAD

**Issue by MFlisar** [deano2390/MaterialShowcaseView#2]
Is it possible to reset all showcases at once? 

`MaterialShowcaseView.resetSingleUse` wraps a private `PrefsManager` and I think the `PrefsManager` should be extended with 

     static void resetShowcases(Context context) {
        SharedPreferences internal = context.getSharedPreferences("material_showcaseview_prefs", 0);
        internal.edit().clear().commit();
    }

and the `MaterialShowcaseView` should offer a function that calls this function

**Comment by deano2390** [comment]
Good idea, i'll implement this shortly

**Comment by deano2390** [comment]
Added a resetAll method in 1.0.2.

https://github.com/deano2390/MaterialShowcaseView/blob/master/library/src/main/java/uk/co/deanwild/materialshowcaseview/MaterialShowcaseView.java#L597
