### ISSUE TITLE
trying to use it in recycler view adapter

### ISSUE THREAD

**Issue by ViTech2019** [deano2390/MaterialShowcaseView#200]
Hey!
Is there any way to use this showCaseView on a specific view inside the recycler view?
I have 5 different cardViews, and I need an explanation for each one of them
hope someone can help me with this
thanks in advance

**Comment by kathir-t** [comment]
@ViTech2019 This is the Issues section. What you are asking for is a doubt. Please delete this issue and post your doubt in online tech forums like StackOverflow.com etc...
