### ISSUE TITLE
Close Button (and some Text) off screen when contentText is too long

### ISSUE THREAD

**Issue by markusressel** [deano2390/MaterialShowcaseView#52]
I've encountered another issue where the close button ("GOT IT" in your example) is rendered off screen when the content text is too long. The content text should be wrapped in a scrollView to always be able to render the close button on screen.

**Comment by markusressel** [comment]
![photo_2015-12-12_16-06-38](https://cloud.githubusercontent.com/assets/14024504/11762537/5d3b02b6-a0ea-11e5-88fa-f2da2caba958.jpg)

**Comment by markusressel** [comment]
The workaround for now is to set `.setDismissOnTouch(true)` but the ShowcaseView should be able to handle this case by itself imo.

**Comment by Zeliret** [comment]
I can confirm this annoying behavior. :(

**Comment by haldertaer** [comment]
Any solution to this problem?

**Comment by markusressel** [comment]
fixed in #53
